### ISSUE TITLE
Refer to actual application forms etc.

### ISSUE THREAD

**Issue by pimotte** [discipl/regelingen-check#13]
Per regeling, include a link to where you can apply

**Comment by hidde-jan** [comment]
TOGS has multiple possible points of entry:
- https://www.rvo.nl/subsidie-en-financieringswijzer/tegemoetkoming-schade-covid-19
- https://www.rvo.nl/subsidie-en-financieringswijzer/tegemoetkoming-schade-covid-19/aanvraagproces/aanvraagprocedure
- https://mijn.rvo.nl/eloket/login-start.html?pageUri=/catalog/openForm.do%3Fpath%3Dcatalog%3A//Regelingen/414NOOD%26create%3Dnew

I don't know which is best.

For Tozo, there isn't a single entrypoint.

**Comment by pimotte** [comment]
The second seems best, for tozo you need to apply with the municipality, so
a note saying so would suffice
