### ISSUE TITLE
Show date of model in interface

### ISSUE THREAD

**Issue by pimotte** [discipl/regelingen-check#20]
May be from model, but could just be hardcoded

**Comment by hidde-jan** [comment]
I see a few validFrom/Until, but they seem to be at the fact level. Is that correct?

**Comment by pimotte** [comment]
Yeah, this is just hardcoded probably. We don't really have model versions
yet. It's just a disclaimer in case something gets changed

**Comment by hidde-jan** [comment]
Do we have a list of these dates?
